### ISSUE TITLE
Cannot publish to Steam Workshop

### ISSUE THREAD

**Issue by JimmyCreekwater** [Nyerguds/CnCTDRAMapEditor#4]
Hello - I have a map that I created in your editor. 

I have published maps in the default CNC editor with no issue, but I cannot open the map created in your editor in CNC remastered default map editor for some reason. 

When I click 'Go To Steam' it does bring me to Steam in the browser, but there is no option to upload anything anywhere that I can find. 

I spent around 10 hours making this map in your editor, so if there's anything I can do to publish it that I'm missing, that'd be great. 

When I try to load the map made in your editor in the default editor, all I get is 'Error loading /% filepath %/ map.mpr' with no other details. 

Other maps load fine in your editor and the default editor, but this one is proving troublesome. 

Thanks for any insight.

**Comment by Nyerguds** [comment]
I'm not entirely sure what you mean. Why are you clicking 'Go To Steam'? You upload the map using the "Publish Map" button.

**Comment by Nyerguds** [comment]
There appears to be a bug with it not saving the published file ID into the map after publishing, though. I'm looking into that one.

The dialog seems to have some other issues, like it not accepting a previously-saved thumbnail without explicitly re-selecting it. I'm giving the whole thing some thorough testing.

**Comment by Nyerguds** [comment]
I'm assuming the main issue here was probably the fact the "Publish Map" button was greyed out. This is caused by a lack of description; fill in any text in the description field and the button gets enabled.

This will be made more intuitive in the next version; the button will always be enabled, but will simply give an error message box when no text is filled in.

**Comment by JimmyCreekwater** [comment]
I am not sure what the issue was, over 2 days the 'Publish Map' button was greyed out, I did have a description - but after checking today all seems well and I was able to publish.

Thanks for the great map editor!
