### ISSUE TITLE
Megamap Mission won't get Published

### ISSUE THREAD

**Issue by john-drak** [Nyerguds/CnCTDRAMapEditor#6]
Hi Nyerguds. I made a singleplayer mission megamap for TD with this editor (v. 1.5.0.1), intended to be used with an appropriate mod. When I tried to publish it on Steam Workshop, a warning window said I couldn't because it was a megamap and it's for TD so it wouldn't work, and I wasn't allowed to publish it. I'm assuming that the editor "thinks" this isn't a singleplayer mission, but I don't know.

Publishing megamap missions should be allowed. I assume this was an oversight. Please look into it. Thanks in advance.

**Comment by Nyerguds** [comment]
Hmm. I indeed never put an exception for singleplayer maps into that code.

I put that restriction in because megamaps might have a potential to make the official servers act weird or crash, but yes, for singpleplayer maps that should be allowed.

I'll look into it.

**Comment by Nyerguds** [comment]
Will be included in v1.5.0.2
